sampling:
  dataset_name: rbm_1m_ood_test
  paths: [/mnt/shared-storage-gpfs2/evobox-share-gpfs2/liuyicong/robometer/hf_rbm_1m_ood_datasets/rbm-1m-ood]
  max_trajectories: 2
  eval_types: [progress]
  base_frames: 12
  progress_type: absolute_first_frame

infer:
  name: openai_compatible
  base_url: BASE_URL
  api_key: API_KEY
  model_id: MODEL_ID


metrics: [progress]
output_dir: /mnt/shared-storage-user/liuyicong/prmeval/evaluation_output
run_name: rbm_1m_ood_openai_compatible_reward_alignment
resume: false
mode: continue